language: node_js
node_js:
  - "10"
  
script:
  - yarn build
after_success: 
  - yarn test --coverage && cat ./coverage/lcov.info | coveralls

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./install/deploy.sh 2
deploy:
  provider: script
  script: docker push codechillaluna/code-chill-client
  on:
    branch: master

notifications:
  email: false
