language: node_js
node_js:
  - "10"
  
script:
  - yarn build
after_success: 
  - yarn test --coverage && cat ./coverage/lcov.info | coveralls

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./install/deploy.sh 1
deploy:
  provider: script
  script: ./install/deploy.sh 1
  on:
    all_branches: true

notifications:
  email: false
