language: node_js
node_js:
  - "10"

before_script:
  - yarn install

script:
  - yarn build
after_success: 
  - yarn test --coverage && cat ./coverage/lcov.info | coveralls

notifications:
  email: false
